### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by 8lers**
pls DON't read comment stupid things like this

### CODE REVIEW

**Comment by bsimmatis** [comment]
No. Bad dog.

**Comment by bsimmatis** [comment]
```{r}
print("weirdo")
```

**Comment by 8lers** [comment]
```{r, echo=FALSE}
print("this is working yay")
```

**Comment by bsimmatis** [comment]
```{r}
print("i haz cheezburgr")
```

**Comment by 8lers** [comment]
```{r}
print("So chzburgr very wow")
```

**Comment by bsimmatis** [comment]
```{r}
print("*sips tea*")
```

**Comment by 8lers** [comment]
OO 
  ( --  )
(     ||    )
^^~~^^

**Comment by bsimmatis** [comment]
A_A
  ( -.- )

**Comment by bsimmatis** [comment]
A_A
  ( -.- )

**Comment by bsimmatis** [comment]
leif...

**Pull request merged**
